spring.application.name=app

# PostgreSQL Configuration - connect via SSH tunnel
spring.datasource.url=jdbc:postgresql://localhost:5433/gigachat
spring.datasource.username=postgres
spring.datasource.password=GitBusRoot
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Firebase / Firestore Configuration
firebase.project.id=gigachat-8aa52
firebase.credentials.path=service-account.json

application.security.jwt.secret-key=abcdefghijklmnopqrstuvwxyz1234567890
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration